/**
 * Typed access to data generated by `npm run ingest`.
 *
 * The ingestion script (scripts/ingestPokopiaData.ts) writes JSON into
 * src/data/generated/. This module gives the rest of the app strongly-typed
 * access plus a few convenient indexes (e.g. by dex number).
 */
import pokemonJson from "./generated/pokemon.json";
import habitatsJson from "./generated/habitats.json";
import itemsJson from "./generated/items.json";
import itemsByFavoriteJson from "./generated/itemsByFavorite.json";
import locationsJson from "./generated/locations.json";
import specialtiesJson from "./generated/specialties.json";
import houseGroupsJson from "./generated/houseGroups.json";
import manifestJson from "./generated/manifest.json";

import type { RegionId, HabitatType } from "./regions";

export type LocationRegionId = RegionId | "dreamIsland";

export interface PokemonHabitat {
  name: string;
  available: Partial<Record<RegionId, boolean>>;
  rarity?: string;
  timesOfDay?: string[];
  weathers?: string[];
}

export interface Pokemon {
  /** Pokopia internal dex number (does NOT match the National Pokedex). */
  number: number;
  numberStr: string;
  name: string;
  /** PokeAPI species slug (e.g. "ho-oh", "tatsugiri"). */
  slug: string;
  /**
   * Official National Pokedex number. Use this for sprites and any cross-
   * reference with the wider Pokemon ecosystem; `null` if not resolved.
   */
  nationalDex: number | null;
  primaryLocation: string;
  specialties: string[];
  idealHabitat: HabitatType | string;
  favorites: string[];
  habitats: PokemonHabitat[];
}

export interface Habitat {
  id: string;
  number: number;
  numberStr: string;
  name: string;
  description: string;
  /** Serebii image filename (e.g. "1.png" or "e1.png"). Use {@link habitatImageUrl}. */
  image: string;
  isEvent: boolean;
}

export interface Item {
  name: string;
  /** Top-level Serebii category: Materials, Food, Furniture, Misc., etc. */
  category: string;
  /** In-game tag shown by Serebii: Decoration, Food, Relaxation, Road, Toy, or "". */
  tag: string;
  description: string;
  /** Serebii image filename (e.g. "honey.png"). Use {@link itemImageUrl}. */
  image: string;
  locations: string[];
}

export interface FavoriteCategory {
  category: string;
  items: { name: string; description: string }[];
}

export interface LocationRegion {
  region: LocationRegionId;
  name: string;
  description: string;
  objective: string;
  materials: string[];
  plantsAndBlocks: string[];
}

export interface Specialty {
  name: string;
  description: string;
}

export interface HouseGroupPokemon {
  number: number;
  numberStr: string;
  name: string;
  favorites: string[];
}

export interface HouseGroup {
  region: RegionId;
  habitatType: HabitatType | string;
  number: number;
  title: string;
  pokemon: HouseGroupPokemon[];
  shared: string[];
  suggestedItems: { favorite: string; items: string[] }[];
}

export interface Manifest {
  generatedAt: string;
  source: string;
  pokemon: number;
  habitats: number;
  items: number;
  itemsByFavorite: number;
  locations: number;
  specialties: number;
  houseGroups: number;
}

export const pokemon = pokemonJson as Pokemon[];
export const habitats = habitatsJson as Habitat[];
export const items = itemsJson as Item[];
export const itemsByFavorite = itemsByFavoriteJson as FavoriteCategory[];
export const locations = locationsJson as LocationRegion[];
export const specialties = specialtiesJson as Specialty[];
export const houseGroups = houseGroupsJson as HouseGroup[];
export const manifest = manifestJson as Manifest;

export const pokemonByDex: Map<number, Pokemon[]> = (() => {
  const m = new Map<number, Pokemon[]>();
  for (const p of pokemon) {
    const arr = m.get(p.number) ?? [];
    arr.push(p);
    m.set(p.number, arr);
  }
  return m;
})();

export const pokemonByName: Map<string, Pokemon> = new Map(
  pokemon.map((p) => [p.name.toLowerCase(), p]),
);

export const itemsByName: Map<string, Item> = new Map(
  items.map((i) => [i.name.toLowerCase(), i]),
);

export const habitatsByName: Map<string, Habitat> = new Map(
  habitats.map((h) => [h.name.toLowerCase(), h]),
);

export const favoriteByCategory: Map<string, FavoriteCategory> = new Map(
  itemsByFavorite.map((f) => [f.category.toLowerCase(), f]),
);

export const locationsByRegion: Map<LocationRegionId, LocationRegion> = new Map(
  locations.map((l) => [l.region, l]),
);

export const houseGroupsByRegion: Map<RegionId, HouseGroup[]> = (() => {
  const m = new Map<RegionId, HouseGroup[]>();
  for (const g of houseGroups) {
    const arr = m.get(g.region) ?? [];
    arr.push(g);
    m.set(g.region, arr);
  }
  return m;
})();

/**
 * Build a public-relative URL for a Pokemon sprite. Sprites are keyed by the
 * official National Pokedex number (resolved via PokeAPI at ingest time),
 * NOT by Pokopia's internal `number` field. Returns `null` if the species
 * could not be resolved.
 */
export function pokemonSpriteUrl(nationalDex: number | null): string | null {
  if (nationalDex == null || !Number.isFinite(nationalDex) || nationalDex <= 0) {
    return null;
  }
  return `/sprites/pokemon/${nationalDex}.png`;
}

/** Serebii habitat icon URL (e.g. /serebii/habitats/1.png). */
export function habitatImageUrl(image: string | null | undefined): string | null {
  if (!image) return null;
  return `/serebii/habitats/${image}`;
}

/** Serebii item icon URL (e.g. /serebii/items/honey.png). */
export function itemImageUrl(image: string | null | undefined): string | null {
  if (!image) return null;
  return `/serebii/items/${image}`;
}
